name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
jobs:
    test_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: '10.19.0'

            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
            - name: Build
              run: npm run build
    # npm-publish:
    #     needs: test_build
    #     name: npm-publish
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@master
    #         - uses: actions/setup-node@master
    #           with:
    #               node-version: '10.19.0'
    #         - name: Install dependencies
    #           run: npm ci
    #         - name: Build
    #           run: npm run build
    #         - name: Publish if version has been updated
    #           uses: pascalgn/npm-publish-action@4f4bf159e299f65d21cd1cbd96fc5d53228036df
    #           with: # All of theses inputs are optional
    #               tag_name: 'v%s'
    #               tag_message: 'v%s'
    #               commit_pattern: "^release (\\S+)"
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}ted
    #               NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
